# Generated by Django 4.1 on 2022-08-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
